name: example
version: 0.0.1
description: A new flutter package project.
author:
homepage:

environment:
  sdk: '>=2-0-0-dev <2.0.0'

dependencies:
  build_config: ^0.2.3
  build_runner: ^0.8.0
  built_viewmodel:
    path: ../built_viewmodel

dev_dependencies:
  built_viewmodel_generator:
    path: ../built_viewmodel_generator
