name: built_viewmodel
version: 1.2.6
description: >
  built_viewmodel to generate ViewModel(s).
  This library is the runtime dependency.
author: Ralph Bergmann <ralph@the4thfloor.eu>
homepage: https://github.com/the4thfloor/built_viewmodel.dart

environment:
  sdk: '>=2-0-0 <3.0.0'

dependencies:
  build_config: ^0.3.1
  flutter:
    sdk: flutter
  quiver: ^2.0.0

dev_dependencies:
  test: any
