name: built_viewmodel
version: 1.2.3
description: >
  built_viewmodel to generate ViewModel(s).
  This library is the runtime dependency.
author: Ralph Bergmann <ralph@the4thfloor.eu>
homepage: https://github.com/the4thfloor/built_viewmodel.dart

environment:
  sdk: '>=2-0-0-dev <2.0.0'

dependencies:
  build_config: ^0.2.5
  flutter:
    sdk: flutter
  quiver: '>=0.21.0 <0.30.0'

dev_dependencies:
  test: any
