name: built_viewmodel_generator
version: 1.2.2
description: >
  built_viewmodel_generator to generate ViewModel(s).
  This library is the dev dependency.
author: Ralph Bergmann <ralph@the4thfloor.eu>
homepage: https://github.com/the4thfloor/built_viewmodel.dart

environment:
  sdk: '>=2-0-0-dev <2.0.0'

dependencies:
  analyzer: '>=0.29.0 <0.32.0'
  build: ^0.11.2
  build_config: ^0.2.5
  code_builder: ^3.0.3
  dart_style: ^1.0.9
  source_gen: ^0.7.5
  quiver: '>=0.21.0 <0.30.0'

dev_dependencies:
  build_runner: ^0.7.5
  test: any
