name: built_viewmodel_generator
version: 1.2.6
description: >
  built_viewmodel_generator to generate ViewModel(s).
  This library is the dev dependency.
author: Ralph Bergmann <ralph@the4thfloor.eu>
homepage: https://github.com/the4thfloor/built_viewmodel.dart

environment:
  sdk: '>=2-0-0 <3.0.0'

dependencies:
  analyzer: ^0.32.4
  build: ^0.12.7
  build_config: ^0.3.1
  code_builder: ^3.1.3
  dart_style: ^1.1.3
  source_gen: ^0.9.1
  quiver: ^2.0.0

dev_dependencies:
  build_runner: ^0.10.2
  test: any
