name: built_viewmodel_generator
version: 0.0.1
description: built_viewmodel_generator
author: Ralph Bergmann <ralph@the4thfloor.eu>
homepage: https://github.com/the4thfloor/built_viewmodel.dart

#environment:
#  sdk: '>=2-0-0-dev <2.0.0'

dependencies:
  analyzer: '>=0.29.0 <0.32.0'
#  build: ^0.12.0
  build_config: ^0.2.5
  code_builder: ^3.0.3
  dart_style: ^1.0.10
  quiver: '>=0.21.0 <0.29.0'
  source_gen: ^0.7.6

dev_dependencies:
  build_runner: ^0.8.0
